baseURL = "https://beths-bon-bons.web.app"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 100
googleAnalytics = "G-FNT7V6192Z"
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Beth's Bon Bon's"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 10

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/Beths-Bon-Bons-111680261346856"

[[params.ananke_socials]]
name = "email"
url = "mailto:bethsbonbons@gmail.com"
label = "mail"
